image: gitpod/workspace-full

tasks:
  - init: |
      git clone https://github.com/flutter/flutter.git -b stable ~/flutter
    command: |
      export PATH="$PATH:$HOME/flutter/bin"
      flutter config --enable-web
      flutter doctor
      flutter create myapp
      cd myapp
      flutter run -d web

vscode:
  extensions:
    - dart-code.flutter
